name: Build, push and deploy Aleph Zero Dashboard to devnet

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-20.04
    environment:
      name: devnet
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v3

      - name: Build and push devnet image
        uses: ./.github/actions/build-and-push
        id: build-devnet
        with:
          environment: devnet
          build_envs: 'VITE_DISABLE_FIAT=1'
          aws_mainnet_access_key_id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws_mainnet_secret_access_key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
    outputs:
      image_tag: ${{ steps.build-devnet.outputs.image_tag }}

  deploy-to-devnet:
    name: Deploy to devnet
    runs-on: ubuntu-20.04
    needs: [build-and-push]
    environment:
      name: devnet
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v3

      - name: Deploy Aleph Zero Dashboard to Devnet
        uses: ./.github/actions/deploy
        id: deploy-devnet
        with:
          environment: devnet
          kustomize_version: ${{ vars.KUSTOMIZE_VERSION }}
          image_tag: ${{ needs.build-and-push.outputs.image_tag }}
          github_token: ${{ secrets.CI_GH_TOKEN }}

  slack-notification:
    name: Slack notification
    runs-on: ubuntu-20.04
    needs: [deploy-to-devnet]
    if: >
      !cancelled() &&
      github.event_name != 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Slack message
        uses: ./.github/actions/slack-notification
        with:
          notify-on: "failure"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV_ONDUTY }}
