name: Aleph Zero Dashboard CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test

  all:
    # This job ensures that all jobs above (now we have just build) are successful.
    needs: [build, validate-locales]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success
