name: GitHub Pages Publish

on:
  push:
    branches: [auto-gh-deploy] # TODO: change to main before merging.

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - run: yarn install
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: New Version
        id: app_version
        uses: PostHog/check-package-version@v2
        with:
          path: "."

      - name: Publish
        if: steps.app_version.outputs.is-new-version == 'true'
        working-directory: "."
        run: yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}