name: Release Automation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          # Commit to start releases from.
          bootstrap-sha: 6b7dc60cece70cfeb4190ac4dacc205112578288
          release-type: node
          package-name: staking-dashboard
